Compatibility of Mark GMail read with TB 68+
acabal/thunderbird-addons pull request #9
Opened 2019-11-01 23:11 UTC by peci1

Not giving up!

2019-11-02 12:26 UTC, tooomm commented
CC @Qrzysio

2019-11-02 15:06 UTC, Qrzysio commented
Well done! It works properly with the newest TB. 
I will test it more and better on weekdays when I receive dozens of emails.

2019-11-04 03:18 UTC, acabal commented
Thanks! I've left some notes. Let me know if an updated version appears to be working OK after a week or so and I can release this to the TB extensions site. (I don't use Gmail any more so I can't test this myself.)

2019-11-04 06:18 UTC, tooomm commented
@acabal No notes visible here.

2019-11-04 16:47 UTC, acabal requested changes

2019-11-04 16:47 UTC, acabal commented on mark-gmail-read/bootstrap.js
> +const { XPCOMUtils } = ChromeUtils.import("resource://gre/modules/XPCOMUtils.jsm");
What does this line do? It looks like we're assigning a const, but it's never used anywhere?

2019-11-04 16:47 UTC, acabal commented on mark-gmail-read/bootstrap.js
> +	console.log("Mark GMail Read: Addon started. Not marking directories '" + markGmailRead.MSG_FOLDER_GMAIL_ALL_MAIL + "', '" + markGmailRead.MSG_FOLDER_GMAIL_IMPORTANT + "' and '" + markGmailRead.MSG_
I would prefer it if we don't output to the console with non-error messages. Well-behaved programs are quiet on success. Instead you can put this kind of informational stuff in the installation instructions (which it looks like you did).

2019-11-04 16:53 UTC, peci1 commented on mark-gmail-read/bootstrap.js
> +const { XPCOMUtils } = ChromeUtils.import("resource://gre/modules/XPCOMUtils.jsm");
It is used: XPCOMUtils.defineLazyServiceGetter in startup()

2019-11-04 16:55 UTC, peci1 commented on mark-gmail-read/bootstrap.js
> +	console.log("Mark GMail Read: Addon started. Not marking directories '" + markGmailRead.MSG_FOLDER_GMAIL_ALL_MAIL + "', '" + markGmailRead.MSG_FOLDER_GMAIL_IMPORTANT + "' and '" + markGmailRead.MSG_
Normally, I wouldn't output. But here, the console message contains the "resolved" config variables, so the user can make sure he had set the correct ones, which is important to know.

2019-11-05 00:20 UTC, acabal commented on mark-gmail-read/bootstrap.js
> +	console.log("Mark GMail Read: Addon started. Not marking directories '" + markGmailRead.MSG_FOLDER_GMAIL_ALL_MAIL + "', '" + markGmailRead.MSG_FOLDER_GMAIL_IMPORTANT + "' and '" + markGmailRead.MSG_
Yes but if they're not going to read the README, they're not going to read the console output either.; I would rather keep it silent. And, in any case, outputting to the console has nothing to do with TB 68 compatibility.

2019-11-05 01:04 UTC, peci1 commented on mark-gmail-read/bootstrap.js
> +	console.log("Mark GMail Read: Addon started. Not marking directories '" + markGmailRead.MSG_FOLDER_GMAIL_ALL_MAIL + "', '" + markGmailRead.MSG_FOLDER_GMAIL_IMPORTANT + "' and '" + markGmailRead.MSG_
Okay, never mind.

2019-11-05 01:05 UTC, peci1 commented
Updated

2019-11-05 03:09 UTC, merged

2019-11-05 03:10 UTC, acabal commented
Great, thanks!